# Generated by Django 4.0.6 on 2022-08-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_yt'),
    ]

    operations = [
        migrations.AddField(
            model_name='yt',
            name='feature_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
